/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectBuffer3;

import java.io.*;
import java.nio.file.Path;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;
public class Home3 extends javax.swing.JFrame {
    JFileChooser dialog = new JFileChooser();

    /**
     * Creates new form Home3
     */
    public Home3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tmpText = new javax.swing.JTextArea();
        jScrollBar1 = new javax.swing.JScrollBar();
        jTextFieldCari = new javax.swing.JTextField();
        jButtonBrowse = new javax.swing.JButton();
        jButtonSimpan = new javax.swing.JButton();
        ButtonBacaBuffer = new javax.swing.JButton();
        ButtonBacaUnBuffer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonSimpanunBuffer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tmpText.setColumns(20);
        tmpText.setRows(5);
        jScrollPane1.setViewportView(tmpText);

        jButtonBrowse.setText("Browse");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });

        jButtonSimpan.setText("Simpan Buffer");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        ButtonBacaBuffer.setText("Tampil Buffered");
        ButtonBacaBuffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBacaBufferActionPerformed(evt);
            }
        });

        ButtonBacaUnBuffer.setText("Tampil UnBuffered");
        ButtonBacaUnBuffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBacaUnBufferActionPerformed(evt);
            }
        });

        jLabel1.setText("  ms");

        jButtonSimpanunBuffer.setText("Simpan unBuffer");
        jButtonSimpanunBuffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanunBufferActionPerformed(evt);
            }
        });

        jLabel2.setText("ms");

        jLabel3.setText("ms");

        jLabel4.setText("  ms");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                        .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(ButtonBacaBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(ButtonBacaUnBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSimpanunBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCari)
                    .addComponent(jButtonBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBacaBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jButtonSimpanunBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonBacaUnBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
    int pFile = dialog.showOpenDialog(this  );        // TODO add your handling code here:
    if (pFile == JFileChooser.APPROVE_OPTION) {
        File file = dialog.getSelectedFile();
        try {
            jTextFieldCari.setText("" + file);
        } catch (Exception e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jButtonBrowseActionPerformed

    private void ButtonBacaBufferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBacaBufferActionPerformed
tmpText.setText(null);        // TODO add your handling code here:
String path = jTextFieldCari.getText();

File file = new File (path);

try {
        long startTime = System.nanoTime(); //startTime
        FileInputStream fstream = new FileInputStream(file);
        DataInputStream in = new DataInputStream(fstream);
        BufferedReader br = new BufferedReader(new InputStreamReader(in));
        String strLine;
        while ((strLine = br.readLine()) !=null) {
            StringTokenizer st = new StringTokenizer(strLine, ".");
            tmpText.setText(tmpText.getText() + st.nextToken()+ "\n" );
            long endTime = System.nanoTime(); //end timer	
            long elapsed = endTime - startTime; //waktu eksekusi
             String waktu = elapsed/1000+" ms"; // microseconds (/1000), millisecond (/1000000)
            jLabel1.setText(waktu);
        }
        in.close();
        
    } catch (Exception e){
        System.out.println("Error" + e.getMessage());
    }
     
    }//GEN-LAST:event_ButtonBacaBufferActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
String path = jTextFieldCari.getText();
        File file = new File(path);
        try {
            long startTime = System.nanoTime(); //startTime
            file.createNewFile();
                PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter(file)));
                out.print(tmpText.getText());
                out.flush();
                long endTime = System.nanoTime(); //end timer	
            long elapsed = endTime - startTime; //waktu eksekusi
             String waktu = elapsed/1000+" ms"; // microseconds (/1000), millisecond (/1000000)
            jLabel3.setText(waktu);
        }catch (Exception e){
            System.out.println("Error : " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void ButtonBacaUnBufferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBacaUnBufferActionPerformed
tmpText.setText(null);        // TODO add your handling code here:
String path = jTextFieldCari.getText();

File file = new File (path);

try {
        long startTime = System.nanoTime(); //startTime
        FileInputStream fstream = new FileInputStream(file);
        DataInputStream in = new DataInputStream(fstream);
        String strLine;
        while ((strLine = in.readLine()) !=null) {
            StringTokenizer st = new StringTokenizer(strLine, ".");
            tmpText.setText(tmpText.getText() + st.nextToken()+ "\n" );
            long endTime = System.nanoTime(); //end timer	
            long elapsed = endTime - startTime; //waktu eksekusi
             String waktu = elapsed/1000+" ms"; // microseconds (/1000), millisecond (/1000000)
            jLabel2.setText(waktu);
        }
        in.close();
        
    } catch (Exception e){
        System.out.println("Error" + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBacaUnBufferActionPerformed

    private void jButtonSimpanunBufferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanunBufferActionPerformed
String path = jTextFieldCari.getText();
        File file = new File(path);
        try {
            long startTime = System.nanoTime(); //startTime
            file.createNewFile();
                PrintWriter out = new PrintWriter(new FileWriter(file));
                out.print(tmpText.getText());
                out.flush();
                 long endTime = System.nanoTime(); //end timer	
            long elapsed = endTime - startTime; //waktu eksekusi
             String waktu = elapsed/1000+" ms"; // microseconds (/1000), millisecond (/1000000)
            jLabel4.setText(waktu);
        }catch (Exception e){
            System.out.println("Error : " + e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSimpanunBufferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBacaBuffer;
    private javax.swing.JButton ButtonBacaUnBuffer;
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonSimpanunBuffer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JTextArea tmpText;
    // End of variables declaration//GEN-END:variables
}
